### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by qbKhanh** [thomas0809/MolScribe#7]
First of all, I want to thank you for your contributions.

I stuck with the following error when trying to run ` bash scripts/train_uspto_joint_chartok_1m680k.sh `:

```
Traceback (most recent call last):
  File "/home/qk/Documents/OCR/MolScribe/train.py", line 606, in <module>
    main()
  File "/home/qk/Documents/OCR/MolScribe/train.py", line 592, in main
    train_loop(args, train_df, valid_df, aux_df, tokenizer, args.save_path)
  File "/home/qk/Documents/OCR/MolScribe/train.py", line 374, in train_loop
    avg_loss, global_step = train_fn(
  File "/home/qk/Documents/OCR/MolScribe/train.py", line 215, in train_fn
    scaler.scale(loss).backward()
  File "/home/qk/anaconda3/envs/MolScribe/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/qk/anaconda3/envs/MolScribe/lib/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [1, 123]] is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

Hope you can reply me soon!
Thank you!

**Comment by thomas0809** [comment]
Hi,

Our experiments should be reproduced under the environment as specified in [setup.py](https://github.com/thomas0809/MolScribe/blob/main/setup.py). 

I am not aware of the error you mentioned. Can you provide more details of your environment?

**Comment by qbKhanh** [comment]
I will give you more infor about my situation:
When I try to` python setup.py install`, an error occured:
```
/home/qk/anaconda3/envs/MolScribe/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/qk/anaconda3/envs/MolScribe/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
zip_safe flag not set; analyzing archive contents...
molscribe.__pycache__.tokenizer.cpython-39: module references __file__
molscribe.indigo.__pycache__.__init__.cpython-39: module references __file__
```
So I must install manually for each required packets.
After installed, I can run `bash scripts/eval_uspto_joint_chartok_1m680k.sh` but not `bash scripts/train_uspto_joint_chartok_1m680k.sh`

AND

How can i show for you my environment?

Thank you!

**Comment by qbKhanh** [comment]
I'm still waiting for your answer!

**Comment by qbKhanh** [comment]
I tried to run forward and backward separately for each part of model: Encoder, GraphPredictor, TransformerDecoderAR. But none of them occur error. I do not know how to fix this bug.

**Comment by qbKhanh** [comment]
I tried also. But this is not a solution for my problem.

**Comment by qbKhanh** [comment]
[My next try]
I added `loss = Variable(loss, requires_grad = True)' before `scaler.scale(loss).backward()` in train.py, I passed the first error and new error occurs:
```
Traceback (most recent call last):
  File "train.py", line 615, in <module>
    main()
  File "train.py", line 601, in main
    train_loop(args, train_df, valid_df, aux_df, tokenizer, args.save_path)
  File "train.py", line 385, in train_loop
    encoder_scheduler, decoder_scheduler, scaler, device, global_step, SUMMARY, args)
  File "train.py", line 227, in train_fn
    scaler.step(encoder_optimizer)
  File "/home/qk/anaconda3/envs/MolScribe/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py", line 336, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
```

**Comment by qbKhanh** [comment]
I found where is really bug!
Your code do not work with batch_size=1 and it will work with batch_size >= 2
I do not know why.
